<?php

$this->borderContainer()->captureStart('testsLayout', array('design' => 'headline'));
                        
// ************* Header *************

$this->contentPane()->captureStart('headerPane', array('region' => 'top'));
?>    
    
Zend Framework Server Library Tests

<?php
echo $this->contentPane()->captureEnd('headerPane');

// ************* Header *************



// ************* Left *************

$this->contentPane()->captureStart('menuPane', array('region'=>'left'));

$tests = array();
$tests['AdvancedLogging'] = 'Advanced Logging';
$tests['Groups'] = 'Groups';

$branches = array();
$branches[] = 'trunk';
$branches[] = '1.6.1';

?>

<div>

<?php foreach( $branches as $branch ) { ?>
  
  <p><b>Branch <?php echo $branch; ?></b></p>  
  
  <?php foreach( $tests as $test_id => $test_label ) { ?>
    <p><a href="/plain/RunServerLibraryTest.php?Library=ZendFramework&Branch=<?php echo $branch; ?>&Test=<?php echo $test_id; ?>" target="testContentIframe"><?php echo $test_label; ?></a></p>  
  <?php } ?>

<?php } ?>

</div>

<?php
echo $this->contentPane()->captureEnd('menuPane');
        

// ************* Left *************


// ************* Main Content *************

$this->contentPane()->captureStart('contentPane',array('region' => 'center'));

?>

<iframe id="testContentIframe" name="testContentIframe" src=""></iframe>

<?php

echo $this->contentPane()->captureEnd('contentPane');


// ************* Main Content *************

echo $this->borderContainer()->captureEnd('testsLayout');

