
<?php
  	$this->headLink()->prependStylesheet('/css/FirefoxExtension-0.2/domplates.css/' . microtime(true), 'screen');
?>

<?php $this->headScript()->appendFile('/js/jquery/jquery-1.2.6.js'); ?>
<?php $this->headScript()->appendFile('/js/domplate/domplate-1.1a.js/' . microtime(true)); ?>
<?php $this->headScript()->appendFile('/js/FirefoxExtension-0.2/domplates.js/' . microtime(true)); ?>

  
<?php $this->headScript()->captureStart(); ?>

$(function() {

    DomplateDebug.setConsole(top.console);
    DomplateDebug.setEnabled(true);


    var logger = new FirePHPLogger();
    logger.setTarget($("#test").get(0));


    logger.log({data:'Data without label',meta:{maxSummaryChars:50}});

    logger.log({label:'Label',data:'Data with label',meta:{maxSummaryChars:50}});

});


<?php $this->headScript()->captureEnd(); ?>


<div id="test"></div>
