<?php

$this->borderContainer()->captureStart('testsLayout', array('design' => 'headline'));
                        
// ************* Header *************

$this->contentPane()->captureStart('headerPane', array('region' => 'top'));
?>    
    
FirePHPCore Server Library Tests

<?php
echo $this->contentPane()->captureEnd('headerPane');

// ************* Header *************



// ************* Left *************

$this->contentPane()->captureStart('menuPane', array('region'=>'left'));
?>

<div>
  
<p><b>Branch 0.1</b></p>  

<p><a href="/plain/RunServerLibraryTest.php?Library=FirePHPCore&Branch=0.1&Test=BasicLoggingObjectOriented" target="testContentIframe">Basic Logging - Object Oriented</a></p>  
<p><a href="/plain/RunServerLibraryTest.php?Library=FirePHPCore&Branch=0.1&Test=BasicLoggingProcedural" target="testContentIframe">Basic Logging - Procedural</a></p>  

<p><b>Branch 0.2</b></p>  

<p><a href="/plain/RunServerLibraryTest.php?Library=FirePHPCore&Branch=0.2&Test=BasicLoggingObjectOriented" target="testContentIframe">Basic Logging - Object Oriented</a></p>  
<p><a href="/plain/RunServerLibraryTest.php?Library=FirePHPCore&Branch=0.2&Test=BasicLoggingProcedural" target="testContentIframe">Basic Logging - Procedural</a></p>  

</div>

<?php
echo $this->contentPane()->captureEnd('menuPane');
        

// ************* Left *************


// ************* Main Content *************

$this->contentPane()->captureStart('contentPane',array('region' => 'center'));

?>

<iframe id="testContentIframe" name="testContentIframe" src=""></iframe>

<?php

echo $this->contentPane()->captureEnd('contentPane');


// ************* Main Content *************

echo $this->borderContainer()->captureEnd('testsLayout');

