<?php

$this->borderContainer()->captureStart('testsLayout', array('design' => 'headline'));
                        
// ************* Header *************

$this->contentPane()->captureStart('headerPane', array('region' => 'top'));
?>    
    
FirePHPCore Server Library Tests

<?php
echo $this->contentPane()->captureEnd('headerPane');

// ************* Header *************



// ************* Left *************

$this->contentPane()->captureStart('menuPane', array('region'=>'left'));

$tests = array();
$tests['BasicLoggingObjectOriented'] = 'Basic Logging - Object Oriented';
$tests['BasicLoggingProcedural'] = 'Basic Logging - Procedural';
$tests['AllVariableTypes'] = 'All Variable Types';
$tests['ComplexVariableValues'] = 'Complex Variable Types';
$tests['ComplexTable'] = 'Complex Table';
$tests['CheckStrictPHP'] = 'Check Strict PHP';
$tests['UTF8'] = 'UTF-8';
$tests['DivisionByZeroTrace'] = 'Division by zero trace';
$tests['Groups'] = 'Groups';
$tests['Aliases'] = 'Aliases';
$tests['ErrorHandler'] = 'Error Handler';
$tests['ExceptionHandler'] = 'Exception Handler';
$tests['StaticClass'] = 'Static Class';
$tests['ObjectMembers'] = 'Object Members';

$branches = array();
$branches[] = '0.1';
$branches[] = '0.2';

?>

<div>

<?php foreach( $branches as $branch ) { ?>
  
  <p><b>Branch <?php echo $branch; ?></b></p>  
  
  <?php foreach( $tests as $test_id => $test_label ) { ?>
    <p><a href="/plain/RunServerLibraryTest.php?Library=FirePHPCore&Branch=<?php echo $branch; ?>&Test=<?php echo $test_id; ?>" target="testContentIframe"><?php echo $test_label; ?></a></p>  
  <?php } ?>

<?php } ?>

</div>

<?php
echo $this->contentPane()->captureEnd('menuPane');
        

// ************* Left *************


// ************* Main Content *************

$this->contentPane()->captureStart('contentPane',array('region' => 'center'));

?>

<iframe id="testContentIframe" name="testContentIframe" src=""></iframe>

<?php

echo $this->contentPane()->captureEnd('contentPane');


// ************* Main Content *************

echo $this->borderContainer()->captureEnd('testsLayout');

