

<?php
  	$this->headLink()->prependStylesheet('/css/FirefoxExtension-0.2/domplates.css', 'screen');
?>


<?php $this->headScript()->captureStart(); ?>
    
		// This is just so domplate works
		
		function FBL() {};
		function FBTrace() {};
		
		if (!top.console || !top.console.firebug)
		{
		    top.console = {
		        log: function() {},
		        time: function() {},
		        timeEnd: function() {}
		    }
		}
		
		function ddd()
		{
			console.log.apply(console, arguments);
		}
		
		function dir()
		{
			console.dir.apply(console, arguments);
		}
		
		function $(id)
		{
		    return document.getElementById(id);
		}	

<?php $this->headScript()->captureEnd(); ?>
    

<?php $this->headScript()->appendFile('/js/jquery/jquery-1.2.6.js'); ?>
<?php $this->headScript()->appendFile('/js/domplate/domplate-debug.js/' . microtime(true)); ?>
<?php $this->headScript()->appendFile('/js/FirefoxExtension-0.2/domplates.js'); ?>

  
<?php $this->headScript()->captureStart(); ?>
	  
          
$(function() {

			with (FBL){		
      
        DomplateDebug.enabled = false;
      
				var testVar = [{"__cftype__":"struct","keyOne":"valueOne","keyTwo":"valueTwo"},"item two","item three"];			

        var formatter = new Formatter();

				formatter.dump.append({value:testVar}, $("#test").get(0));			

			}

});


<?php $this->headScript()->captureEnd(); ?>


<div id="test"></div>
