<?php print $this->doctype(); ?>
<html>
    <head>
        <title>FirePHP Development Application</title>
        
				<script type="text/javascript">
				//<!--
				<?php echo $this->partial('_partials/header.js'); ?>
				//-->
				</script>
        
        <?php echo $this->dojo()
                        ->enable()
                        ->setLocalPath('js/dojo/dojo.js')
						            ->setDjConfigOption('usePlainJson', true)
						            ->addStyleSheetModule('dijit.themes.tundra')
						            ->addStylesheet('/css/default.css')
					           	  ->requireModule('dojo.rpc.JsonService')
						            ->requireModule('dojo.io.script');
				?>

				<?php $this->headScript()->appendFile('/js/jquery/jquery-1.2.6.js'); ?>

				<?php
				$this->headMeta()->appendHttpEquiv('expires', 
				                                   'Wed, 26 Feb 1997 08:21:57 GMT')
				                 ->appendHttpEquiv('pragma', 'no-cache')
				                 ->appendHttpEquiv('Cache-Control', 'no-cache');
				?>                 

        <?php echo $this->headMeta(); ?>

        <?php echo $this->headScript(); ?>

    </head>
    <body class="tundra">
        <?php echo  $this->layout()->content; ?>
    </body>
</html>