<?php print $this->doctype(); ?>
<html>
    <head>
        <title>...</title>
        
				<script type="text/javascript">
				//<!--
				<?php echo $this->partial('_partials/header.js'); ?>
				//-->
				</script>
        
        
        <?php echo $this->dojo()
                        ->enable()
//						            ->setCdnBase(Zend_Dojo::CDN_BASE_AOL)
                        ->setLocalPath('js2/dojo/dojo.js')
						            ->setDjConfigOption('usePlainJson', true)
						            ->addStyleSheetModule('dijit.themes.tundra')
					           	  ->requireModule('dojo.rpc.JsonService')
						            ->requireModule('dojo.io.script');

Zend_Registry::get('logger')->debug('This is a layout debug message');

				?>

        <?php echo $this->headScript(); ?>

    </head>
    <body class="tundra">
        <?php echo  $this->layout()->content; ?>
    </body>
</html>