<?php print $this->doctype(); ?>
<html>
    <head>
        <title>FirePHP Development Application</title>
        <style type="text/css">
				<!--
				    @import "/css/default.css";
				-->
				</style>

				<?php
				$this->headMeta()->appendHttpEquiv('expires', 
				                                   'Wed, 26 Feb 1997 08:21:57 GMT')
				                 ->appendHttpEquiv('pragma', 'no-cache')
				                 ->appendHttpEquiv('Cache-Control', 'no-cache');
				?>                 

        <?php echo $this->headMeta(); ?>
        
        <?php echo $this->headScript(); ?>
        
    </head>
    <body>
      
        <?php echo  $this->layout()->content; ?>

    </body>
</html>
