<h2>Dojo JSON-RPC Demo</h2>

<input name="foo" type="button" value="Demo" onClick="demoRpc()"/>

<?php $this->headScript()->captureStart(); ?>
    
function demoRpc()
{
    var myObject = new dojo.rpc.JsonService('json-rpc/Server');
    console.log(myObject.bar());
}

<?php $this->headScript()->captureEnd(); ?>



<?php 

print $this->accordionPane(
    'p1', 
    'Pane 1 Content', 
    array(
        'title' => 'Pane Title',
    ),
    array(
        'style' => 'background-color: lightgray;'
    )
);


print $this->accordionContainer(
    'accordion1', 
    
    $this->accordionPane(
    'p1', 
    'Pane 1 Content', 
    array(
        'title' => 'Pane Title',
    ),
    array(
        'style' => 'background-color: lightgray;'
    )
).
$this->accordionPane(
    'p1', 
    'Pane 1 Content', 
    array(
        'title' => 'Pane Title',
    ),
    array(
        'style' => 'background-color: lightgray;'
    )
)
, 
    array(
        'duration' => 200,
    ),
    array(
        'style' => 'width: 200px; height: 300px;',
    )
);


?>


<div id="accordion1">
    <div id="p1">
    </div>
    <div id="p2">
    </div>
</div>
