<?php

$this->borderContainer()->captureStart('masterLayout', array('design' => 'headline'));
                        
// ************* Header *************

echo $this->contentPane(
    'headerPane',
    'FirePHP Development Application',
    array('region' => 'top'));

// ************* Header *************



// ************* Left *************

$this->accordionContainer()->captureStart('menuAccordion', array('region'=>'left'));
    
echo $this->accordionPane(
    'version_0_1_menuPane', 
    'Pane 1 Content', 
    array('title' => 'Version 0.1'));
    
$this->accordionPane()->captureStart('version_0_2_menuPane', array('title' => 'Version 0.2', 'selected'=>true));
?>
<div>
  
<p><a target="contentIframe" href="http://code.google.com/p/firephp/source/browse/branches/FirefoxExtension-0.2">Use branches/FirefoxExtension-0.2 code</a><p>

<h3>Domplate Templates</h3>

<div style="padding-left: 10px; padding-top: 0px;">

  <p><a target="contentIframe" href="Domplate/Log">Log</a><p>

</div>

</div>
<?php
echo $this->accordionPane()->captureEnd('version_0_2_menuPane');

    
echo $this->accordionContainer()->captureEnd('menuAccordion');

// ************* Left *************



// ************* Main Content *************

$this->contentPane()->captureStart('contentPane',array('region' => 'center'));

?>

<iframe id="contentIframe" name="contentIframe" src=""></iframe>

<?php

echo $this->contentPane()->captureEnd('contentPane');


// ************* Main Content *************



// ************* Footer *************

echo $this->contentPane(
    'footerPane',
    'Copyright &copy; <a target="_blank" href="http://www.christophdorn.com/">Christoph Dorn</a>',
    array('region' => 'bottom'));

// ************* Footer *************

echo $this->borderContainer()->captureEnd('masterLayout');

