<h2>Dojo JSON-RPC Demo</h2>

<input name="foo" type="button" value="Demo" onClick="demoRpc()"/>

<?php
$this->dojo()->enable()
             ->setLocalPath('js/dojo/dojo.js')
             ->addStyleSheetModule('dijit.themes.tundra')
             ->requireModule('dojo.rpc.JsonService');
$this->headScript()->captureStart();
?>

function demoRpc()
{
    var myObject = new dojo.rpc.JsonService('json-rpc/Server');
    console.log(myObject.bar());
}

<?php $this->headScript()->captureEnd(); ?>